export const Colors = {
  shieldPurple:      '#3C3489',
  shieldPurpleLight: '#EEEDFE',
  shieldPurpleDark:  '#26215C',
  sosRed:            '#C62828',
  sosRedDark:        '#B71C1C',
  sosRedLight:       '#FFEBEE',
  safeGreen:         '#2E7D32',
  safeGreenLight:    '#E8F5E9',
  background:        '#F5F4F0',
  surface:           '#FFFFFF',
  textPrimary:       '#1A1A18',
  textSecondary:     '#6B6A65',
  border:            '#E0DED8',
  white:             '#FFFFFF',
  black:             '#000000',
  answerGreen:       '#1B5E20',
  declineRed:        '#B71C1C',
  callBg:            '#1A1A1A',
  amber:             '#E65100',
  amberLight:        '#FFF3E0',
  blue:              '#1565C0',
  blueLight:         '#E3F2FD',
};
